data:
  dataset_folder: data
  train_dataset: train.csv
  val_dataset: dev.csv
  test_dataset: test.csv
  use_id: False # nếu set là True thì có sử dụng thông tin id, ngược lại thì không

tokenizer:
  padding: max_length
  max_input_length: 50
  truncation: True

text_embedding:
  type: pretrained #có 3 loại, pretrained, tf_idf, count_vec
  add_new_token: False
  text_encoder: bert-base-multilingual-cased
  freeze: False


model:
  type_model: bert

train:
  output_dir: checkpoint
  seed: 12345
  num_train_epochs: 100
  patience: 5
  learning_rate: 1.0e-5
  weight_decay: 0.01
  metric_for_best_model: f1
  per_device_train_batch_size: 8
  per_device_valid_batch_size: 8

inference:
  with_labels: True
  test_dataset: /content/data/test.csv
  batch_size: 2048